require("items.apple")
require("items.menus")
require("items.spaces")
require("items.front_app")
require("items.calendar")
-- require("items.uname")
require("items.volume")
require("items.battery")
require("items.media")
require("items.control_center")
-- require("items.menu_toggle")
